#+TITLE: inspire.el
#+CREATOR: Simon Lin
#+OPTIONS: toc:nil

inspire.el is an Emacs interface for literature and references searching on the high energy article database [[https://inspirehep.net][inspirehep]].

* Common usage

inspire.el provides two main entry functions for searching on [[https://inspirehep.net][inspirehep]]:
~inspire-literature-search~ for literature lookup and ~inspire-author-search~ for author lookup.
The [[https://help.inspirehep.net/knowledge-base/inspire-paper-search/][SPIRES syntax]] is available for ~inspire-literature-search~ function.
inspire.el will then pop-up a list of records where one can browse and examine detailed information for each record.


In the record list, use ~n~ and ~p~ to navigate the list.

Other useful commands and their default bindings:
+ ~u (inspire-open-url)~ : open the web page associated to the item
+ ~d (inspire-download-pdf)~: download pdf from a selection source
+ ~b (inspire-get-bibtex)~: export the bibtex entry to a temporary buffer
+ ~r (inspire-reference-search)~ and ~c (inspire-citation-search)~: look up references and citations for the current record
 You can also click on references and citations button to initiate the same searches.
+ ~[ (inspire-previous-search)~ and ~] (inspire-next-searchh)~: navigate through the search history
+ ~q (inspire-exit)~: exit the record list

* Customization
TBD

* TODO list
+ insert bib info to database
+ cross searching record authors
+ show experiment info in author page
