#+TITLE: inspire.el
#+CREATOR: Simon Lin
#+OPTIONS: toc:nil

inspire.el is an Emacs interface for literature and references searching on the high energy article database [[https://inspirehep.net][inspirehep]].

* Common usage

inspire.el provides two main entry functions for searching on [[https://inspirehep.net][inspirehep]]:
~inspire-literature-search~ for literature lookup and ~inspire-author-search~ for author lookup.
The [[https://help.inspirehep.net/knowledge-base/inspire-paper-search/][SPIRES syntax]] is available for ~inspire-literature-search~ function.
inspire.el will then pop-up a list of records where one can browse and examine detailed information for each record.

In the record list, use ~n~ and ~p~ to navigate the list.
Use ~u~ to open the web page associated to the item.
Use ~b~ to export the bibtex entry to a temporary buffer.
Click on the references and citations button to lookup for papers referencing or citing the item.
Use ~[~ and ~]~ to navigate through the search history.
Finally, press ~q~ to exit the record list.

* Customization
TBD

* TODO list
+ download PDF function
+ keymap for cross reference searching
+ insert bib info to database
+ cross searching record authors
+ show experiment info in author page
